name: Build and Run Go Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Settt up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Build Go program
        run: |
          go build hello.go

      - name: Run Go program
        run: |
          ./hello
